/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Apiv1exploreraddressOutputs;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block
 **/
@ApiModel(description = "BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block")
public class Apiv1pendingTxsTransaction {
  
  @SerializedName("outputs")
  private List<Apiv1exploreraddressOutputs> outputs = null;
  @SerializedName("inner_hash")
  private String innerHash = null;
  @SerializedName("inputs")
  private List<String> inputs = null;
  @SerializedName("sigs")
  private List<String> sigs = null;
  @SerializedName("length")
  private Integer length = null;
  @SerializedName("txid")
  private String txid = null;
  @SerializedName("type")
  private Integer type = null;
  @SerializedName("timestamp")
  private Integer timestamp = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Apiv1exploreraddressOutputs> getOutputs() {
    return outputs;
  }
  public void setOutputs(List<Apiv1exploreraddressOutputs> outputs) {
    this.outputs = outputs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInnerHash() {
    return innerHash;
  }
  public void setInnerHash(String innerHash) {
    this.innerHash = innerHash;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getInputs() {
    return inputs;
  }
  public void setInputs(List<String> inputs) {
    this.inputs = inputs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getSigs() {
    return sigs;
  }
  public void setSigs(List<String> sigs) {
    this.sigs = sigs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getLength() {
    return length;
  }
  public void setLength(Integer length) {
    this.length = length;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTxid() {
    return txid;
  }
  public void setTxid(String txid) {
    this.txid = txid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getType() {
    return type;
  }
  public void setType(Integer type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1pendingTxsTransaction apiv1pendingTxsTransaction = (Apiv1pendingTxsTransaction) o;
    return (this.outputs == null ? apiv1pendingTxsTransaction.outputs == null : this.outputs.equals(apiv1pendingTxsTransaction.outputs)) &&
        (this.innerHash == null ? apiv1pendingTxsTransaction.innerHash == null : this.innerHash.equals(apiv1pendingTxsTransaction.innerHash)) &&
        (this.inputs == null ? apiv1pendingTxsTransaction.inputs == null : this.inputs.equals(apiv1pendingTxsTransaction.inputs)) &&
        (this.sigs == null ? apiv1pendingTxsTransaction.sigs == null : this.sigs.equals(apiv1pendingTxsTransaction.sigs)) &&
        (this.length == null ? apiv1pendingTxsTransaction.length == null : this.length.equals(apiv1pendingTxsTransaction.length)) &&
        (this.txid == null ? apiv1pendingTxsTransaction.txid == null : this.txid.equals(apiv1pendingTxsTransaction.txid)) &&
        (this.type == null ? apiv1pendingTxsTransaction.type == null : this.type.equals(apiv1pendingTxsTransaction.type)) &&
        (this.timestamp == null ? apiv1pendingTxsTransaction.timestamp == null : this.timestamp.equals(apiv1pendingTxsTransaction.timestamp));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.outputs == null ? 0: this.outputs.hashCode());
    result = 31 * result + (this.innerHash == null ? 0: this.innerHash.hashCode());
    result = 31 * result + (this.inputs == null ? 0: this.inputs.hashCode());
    result = 31 * result + (this.sigs == null ? 0: this.sigs.hashCode());
    result = 31 * result + (this.length == null ? 0: this.length.hashCode());
    result = 31 * result + (this.txid == null ? 0: this.txid.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1pendingTxsTransaction {\n");
    
    sb.append("  outputs: ").append(outputs).append("\n");
    sb.append("  innerHash: ").append(innerHash).append("\n");
    sb.append("  inputs: ").append(inputs).append("\n");
    sb.append("  sigs: ").append(sigs).append("\n");
    sb.append("  length: ").append(length).append("\n");
    sb.append("  txid: ").append(txid).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
