/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Apiv1exploreraddressInputs {
  
  @SerializedName("owner")
  private String owner = null;
  @SerializedName("hours")
  private Long hours = null;
  @SerializedName("calculated_hours")
  private Long calculatedHours = null;
  @SerializedName("coins")
  private String coins = null;
  @SerializedName("uxid")
  private String uxid = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOwner() {
    return owner;
  }
  public void setOwner(String owner) {
    this.owner = owner;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getHours() {
    return hours;
  }
  public void setHours(Long hours) {
    this.hours = hours;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getCalculatedHours() {
    return calculatedHours;
  }
  public void setCalculatedHours(Long calculatedHours) {
    this.calculatedHours = calculatedHours;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCoins() {
    return coins;
  }
  public void setCoins(String coins) {
    this.coins = coins;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUxid() {
    return uxid;
  }
  public void setUxid(String uxid) {
    this.uxid = uxid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1exploreraddressInputs apiv1exploreraddressInputs = (Apiv1exploreraddressInputs) o;
    return (this.owner == null ? apiv1exploreraddressInputs.owner == null : this.owner.equals(apiv1exploreraddressInputs.owner)) &&
        (this.hours == null ? apiv1exploreraddressInputs.hours == null : this.hours.equals(apiv1exploreraddressInputs.hours)) &&
        (this.calculatedHours == null ? apiv1exploreraddressInputs.calculatedHours == null : this.calculatedHours.equals(apiv1exploreraddressInputs.calculatedHours)) &&
        (this.coins == null ? apiv1exploreraddressInputs.coins == null : this.coins.equals(apiv1exploreraddressInputs.coins)) &&
        (this.uxid == null ? apiv1exploreraddressInputs.uxid == null : this.uxid.equals(apiv1exploreraddressInputs.uxid));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.owner == null ? 0: this.owner.hashCode());
    result = 31 * result + (this.hours == null ? 0: this.hours.hashCode());
    result = 31 * result + (this.calculatedHours == null ? 0: this.calculatedHours.hashCode());
    result = 31 * result + (this.coins == null ? 0: this.coins.hashCode());
    result = 31 * result + (this.uxid == null ? 0: this.uxid.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1exploreraddressInputs {\n");
    
    sb.append("  owner: ").append(owner).append("\n");
    sb.append("  hours: ").append(hours).append("\n");
    sb.append("  calculatedHours: ").append(calculatedHours).append("\n");
    sb.append("  coins: ").append(coins).append("\n");
    sb.append("  uxid: ").append(uxid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
