/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Apiv1walletsMeta {
  
  @SerializedName("filename")
  private String filename = null;
  @SerializedName("encrypted")
  private Boolean encrypted = null;
  @SerializedName("crypto_type")
  private String cryptoType = null;
  @SerializedName("label")
  private String label = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("version")
  private String version = null;
  @SerializedName("coin")
  private String coin = null;
  @SerializedName("timestamp")
  private Integer timestamp = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFilename() {
    return filename;
  }
  public void setFilename(String filename) {
    this.filename = filename;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getEncrypted() {
    return encrypted;
  }
  public void setEncrypted(Boolean encrypted) {
    this.encrypted = encrypted;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCryptoType() {
    return cryptoType;
  }
  public void setCryptoType(String cryptoType) {
    this.cryptoType = cryptoType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }
  public void setLabel(String label) {
    this.label = label;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }
  public void setVersion(String version) {
    this.version = version;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCoin() {
    return coin;
  }
  public void setCoin(String coin) {
    this.coin = coin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1walletsMeta apiv1walletsMeta = (Apiv1walletsMeta) o;
    return (this.filename == null ? apiv1walletsMeta.filename == null : this.filename.equals(apiv1walletsMeta.filename)) &&
        (this.encrypted == null ? apiv1walletsMeta.encrypted == null : this.encrypted.equals(apiv1walletsMeta.encrypted)) &&
        (this.cryptoType == null ? apiv1walletsMeta.cryptoType == null : this.cryptoType.equals(apiv1walletsMeta.cryptoType)) &&
        (this.label == null ? apiv1walletsMeta.label == null : this.label.equals(apiv1walletsMeta.label)) &&
        (this.type == null ? apiv1walletsMeta.type == null : this.type.equals(apiv1walletsMeta.type)) &&
        (this.version == null ? apiv1walletsMeta.version == null : this.version.equals(apiv1walletsMeta.version)) &&
        (this.coin == null ? apiv1walletsMeta.coin == null : this.coin.equals(apiv1walletsMeta.coin)) &&
        (this.timestamp == null ? apiv1walletsMeta.timestamp == null : this.timestamp.equals(apiv1walletsMeta.timestamp));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.filename == null ? 0: this.filename.hashCode());
    result = 31 * result + (this.encrypted == null ? 0: this.encrypted.hashCode());
    result = 31 * result + (this.cryptoType == null ? 0: this.cryptoType.hashCode());
    result = 31 * result + (this.label == null ? 0: this.label.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.version == null ? 0: this.version.hashCode());
    result = 31 * result + (this.coin == null ? 0: this.coin.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1walletsMeta {\n");
    
    sb.append("  filename: ").append(filename).append("\n");
    sb.append("  encrypted: ").append(encrypted).append("\n");
    sb.append("  cryptoType: ").append(cryptoType).append("\n");
    sb.append("  label: ").append(label).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  version: ").append(version).append("\n");
    sb.append("  coin: ").append(coin).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
