/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Apiv1wallettransactionTo {
  
  @SerializedName("hours")
  private Long hours = null;
  @SerializedName("address")
  private String address = null;
  @SerializedName("coins")
  private Long coins = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getHours() {
    return hours;
  }
  public void setHours(Long hours) {
    this.hours = hours;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getCoins() {
    return coins;
  }
  public void setCoins(Long coins) {
    this.coins = coins;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1wallettransactionTo apiv1wallettransactionTo = (Apiv1wallettransactionTo) o;
    return (this.hours == null ? apiv1wallettransactionTo.hours == null : this.hours.equals(apiv1wallettransactionTo.hours)) &&
        (this.address == null ? apiv1wallettransactionTo.address == null : this.address.equals(apiv1wallettransactionTo.address)) &&
        (this.coins == null ? apiv1wallettransactionTo.coins == null : this.coins.equals(apiv1wallettransactionTo.coins));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.hours == null ? 0: this.hours.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.coins == null ? 0: this.coins.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1wallettransactionTo {\n");
    
    sb.append("  hours: ").append(hours).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  coins: ").append(coins).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
