/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Apiv1exploreraddressOutputs {
  
  @SerializedName("hours")
  private Long hours = null;
  @SerializedName("dst")
  private String dst = null;
  @SerializedName("coins")
  private String coins = null;
  @SerializedName("uxid")
  private String uxid = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getHours() {
    return hours;
  }
  public void setHours(Long hours) {
    this.hours = hours;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDst() {
    return dst;
  }
  public void setDst(String dst) {
    this.dst = dst;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCoins() {
    return coins;
  }
  public void setCoins(String coins) {
    this.coins = coins;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUxid() {
    return uxid;
  }
  public void setUxid(String uxid) {
    this.uxid = uxid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1exploreraddressOutputs apiv1exploreraddressOutputs = (Apiv1exploreraddressOutputs) o;
    return (this.hours == null ? apiv1exploreraddressOutputs.hours == null : this.hours.equals(apiv1exploreraddressOutputs.hours)) &&
        (this.dst == null ? apiv1exploreraddressOutputs.dst == null : this.dst.equals(apiv1exploreraddressOutputs.dst)) &&
        (this.coins == null ? apiv1exploreraddressOutputs.coins == null : this.coins.equals(apiv1exploreraddressOutputs.coins)) &&
        (this.uxid == null ? apiv1exploreraddressOutputs.uxid == null : this.uxid.equals(apiv1exploreraddressOutputs.uxid));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.hours == null ? 0: this.hours.hashCode());
    result = 31 * result + (this.dst == null ? 0: this.dst.hashCode());
    result = 31 * result + (this.coins == null ? 0: this.coins.hashCode());
    result = 31 * result + (this.uxid == null ? 0: this.uxid.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1exploreraddressOutputs {\n");
    
    sb.append("  hours: ").append(hours).append("\n");
    sb.append("  dst: ").append(dst).append("\n");
    sb.append("  coins: ").append(coins).append("\n");
    sb.append("  uxid: ").append(uxid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
