/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Apiv1exploreraddressStatus {
  
  @SerializedName("unconfirmed")
  private Boolean unconfirmed = null;
  @SerializedName("block_seq")
  private Long blockSeq = null;
  @SerializedName("label")
  private Long label = null;
  @SerializedName("confirmed")
  private Boolean confirmed = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getUnconfirmed() {
    return unconfirmed;
  }
  public void setUnconfirmed(Boolean unconfirmed) {
    this.unconfirmed = unconfirmed;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getBlockSeq() {
    return blockSeq;
  }
  public void setBlockSeq(Long blockSeq) {
    this.blockSeq = blockSeq;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getLabel() {
    return label;
  }
  public void setLabel(Long label) {
    this.label = label;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getConfirmed() {
    return confirmed;
  }
  public void setConfirmed(Boolean confirmed) {
    this.confirmed = confirmed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1exploreraddressStatus apiv1exploreraddressStatus = (Apiv1exploreraddressStatus) o;
    return (this.unconfirmed == null ? apiv1exploreraddressStatus.unconfirmed == null : this.unconfirmed.equals(apiv1exploreraddressStatus.unconfirmed)) &&
        (this.blockSeq == null ? apiv1exploreraddressStatus.blockSeq == null : this.blockSeq.equals(apiv1exploreraddressStatus.blockSeq)) &&
        (this.label == null ? apiv1exploreraddressStatus.label == null : this.label.equals(apiv1exploreraddressStatus.label)) &&
        (this.confirmed == null ? apiv1exploreraddressStatus.confirmed == null : this.confirmed.equals(apiv1exploreraddressStatus.confirmed));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.unconfirmed == null ? 0: this.unconfirmed.hashCode());
    result = 31 * result + (this.blockSeq == null ? 0: this.blockSeq.hashCode());
    result = 31 * result + (this.label == null ? 0: this.label.hashCode());
    result = 31 * result + (this.confirmed == null ? 0: this.confirmed.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1exploreraddressStatus {\n");
    
    sb.append("  unconfirmed: ").append(unconfirmed).append("\n");
    sb.append("  blockSeq: ").append(blockSeq).append("\n");
    sb.append("  label: ").append(label).append("\n");
    sb.append("  confirmed: ").append(confirmed).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
