/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.Apiv1pendingTxsTransaction;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2004 {
  
  @SerializedName("announced")
  private String announced = null;
  @SerializedName("is_valid")
  private Boolean isValid = null;
  @SerializedName("checked")
  private String checked = null;
  @SerializedName("received")
  private String received = null;
  @SerializedName("transaction")
  private Apiv1pendingTxsTransaction transaction = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAnnounced() {
    return announced;
  }
  public void setAnnounced(String announced) {
    this.announced = announced;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsValid() {
    return isValid;
  }
  public void setIsValid(Boolean isValid) {
    this.isValid = isValid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getChecked() {
    return checked;
  }
  public void setChecked(String checked) {
    this.checked = checked;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getReceived() {
    return received;
  }
  public void setReceived(String received) {
    this.received = received;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Apiv1pendingTxsTransaction getTransaction() {
    return transaction;
  }
  public void setTransaction(Apiv1pendingTxsTransaction transaction) {
    this.transaction = transaction;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return (this.announced == null ? inlineResponse2004.announced == null : this.announced.equals(inlineResponse2004.announced)) &&
        (this.isValid == null ? inlineResponse2004.isValid == null : this.isValid.equals(inlineResponse2004.isValid)) &&
        (this.checked == null ? inlineResponse2004.checked == null : this.checked.equals(inlineResponse2004.checked)) &&
        (this.received == null ? inlineResponse2004.received == null : this.received.equals(inlineResponse2004.received)) &&
        (this.transaction == null ? inlineResponse2004.transaction == null : this.transaction.equals(inlineResponse2004.transaction));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.announced == null ? 0: this.announced.hashCode());
    result = 31 * result + (this.isValid == null ? 0: this.isValid.hashCode());
    result = 31 * result + (this.checked == null ? 0: this.checked.hashCode());
    result = 31 * result + (this.received == null ? 0: this.received.hashCode());
    result = 31 * result + (this.transaction == null ? 0: this.transaction.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("  announced: ").append(announced).append("\n");
    sb.append("  isValid: ").append(isValid).append("\n");
    sb.append("  checked: ").append(checked).append("\n");
    sb.append("  received: ").append(received).append("\n");
    sb.append("  transaction: ").append(transaction).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
