/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Represent unconfirmed transactions
 **/
@ApiModel(description = "Represent unconfirmed transactions")
public class InlineResponse2003UnconfirmedVerifyTransaction {
  
  @SerializedName("burn_factor")
  private Integer burnFactor = null;
  @SerializedName("max_transaction_size")
  private Integer maxTransactionSize = null;
  @SerializedName("max_decimals")
  private Integer maxDecimals = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getBurnFactor() {
    return burnFactor;
  }
  public void setBurnFactor(Integer burnFactor) {
    this.burnFactor = burnFactor;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxTransactionSize() {
    return maxTransactionSize;
  }
  public void setMaxTransactionSize(Integer maxTransactionSize) {
    this.maxTransactionSize = maxTransactionSize;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxDecimals() {
    return maxDecimals;
  }
  public void setMaxDecimals(Integer maxDecimals) {
    this.maxDecimals = maxDecimals;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003UnconfirmedVerifyTransaction inlineResponse2003UnconfirmedVerifyTransaction = (InlineResponse2003UnconfirmedVerifyTransaction) o;
    return (this.burnFactor == null ? inlineResponse2003UnconfirmedVerifyTransaction.burnFactor == null : this.burnFactor.equals(inlineResponse2003UnconfirmedVerifyTransaction.burnFactor)) &&
        (this.maxTransactionSize == null ? inlineResponse2003UnconfirmedVerifyTransaction.maxTransactionSize == null : this.maxTransactionSize.equals(inlineResponse2003UnconfirmedVerifyTransaction.maxTransactionSize)) &&
        (this.maxDecimals == null ? inlineResponse2003UnconfirmedVerifyTransaction.maxDecimals == null : this.maxDecimals.equals(inlineResponse2003UnconfirmedVerifyTransaction.maxDecimals));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.burnFactor == null ? 0: this.burnFactor.hashCode());
    result = 31 * result + (this.maxTransactionSize == null ? 0: this.maxTransactionSize.hashCode());
    result = 31 * result + (this.maxDecimals == null ? 0: this.maxDecimals.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003UnconfirmedVerifyTransaction {\n");
    
    sb.append("  burnFactor: ").append(burnFactor).append("\n");
    sb.append("  maxTransactionSize: ").append(maxTransactionSize).append("\n");
    sb.append("  maxDecimals: ").append(maxDecimals).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
