/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.InlineResponse2003UnconfirmedVerifyTransaction;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2003 {
  
  @SerializedName("last_received")
  private Long lastReceived = null;
  @SerializedName("last_sent")
  private Long lastSent = null;
  @SerializedName("outgoing")
  private Boolean outgoing = null;
  @SerializedName("mirror")
  private Integer mirror = null;
  @SerializedName("address")
  private String address = null;
  @SerializedName("listen_port")
  private Integer listenPort = null;
  @SerializedName("is_trusted_peer")
  private Boolean isTrustedPeer = null;
  @SerializedName("connected_at")
  private Long connectedAt = null;
  @SerializedName("unconfirmed_verify_transaction")
  private InlineResponse2003UnconfirmedVerifyTransaction unconfirmedVerifyTransaction = null;
  @SerializedName("id")
  private Long id = null;
  public enum StateEnum {
     pending,  connected,  introduced, 
  };
  @SerializedName("state")
  private StateEnum state = null;
  @SerializedName("user_agent")
  private String userAgent = null;
  @SerializedName("height")
  private Long height = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getLastReceived() {
    return lastReceived;
  }
  public void setLastReceived(Long lastReceived) {
    this.lastReceived = lastReceived;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getLastSent() {
    return lastSent;
  }
  public void setLastSent(Long lastSent) {
    this.lastSent = lastSent;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getOutgoing() {
    return outgoing;
  }
  public void setOutgoing(Boolean outgoing) {
    this.outgoing = outgoing;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMirror() {
    return mirror;
  }
  public void setMirror(Integer mirror) {
    this.mirror = mirror;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getListenPort() {
    return listenPort;
  }
  public void setListenPort(Integer listenPort) {
    this.listenPort = listenPort;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsTrustedPeer() {
    return isTrustedPeer;
  }
  public void setIsTrustedPeer(Boolean isTrustedPeer) {
    this.isTrustedPeer = isTrustedPeer;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getConnectedAt() {
    return connectedAt;
  }
  public void setConnectedAt(Long connectedAt) {
    this.connectedAt = connectedAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse2003UnconfirmedVerifyTransaction getUnconfirmedVerifyTransaction() {
    return unconfirmedVerifyTransaction;
  }
  public void setUnconfirmedVerifyTransaction(InlineResponse2003UnconfirmedVerifyTransaction unconfirmedVerifyTransaction) {
    this.unconfirmedVerifyTransaction = unconfirmedVerifyTransaction;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public StateEnum getState() {
    return state;
  }
  public void setState(StateEnum state) {
    this.state = state;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserAgent() {
    return userAgent;
  }
  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getHeight() {
    return height;
  }
  public void setHeight(Long height) {
    this.height = height;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return (this.lastReceived == null ? inlineResponse2003.lastReceived == null : this.lastReceived.equals(inlineResponse2003.lastReceived)) &&
        (this.lastSent == null ? inlineResponse2003.lastSent == null : this.lastSent.equals(inlineResponse2003.lastSent)) &&
        (this.outgoing == null ? inlineResponse2003.outgoing == null : this.outgoing.equals(inlineResponse2003.outgoing)) &&
        (this.mirror == null ? inlineResponse2003.mirror == null : this.mirror.equals(inlineResponse2003.mirror)) &&
        (this.address == null ? inlineResponse2003.address == null : this.address.equals(inlineResponse2003.address)) &&
        (this.listenPort == null ? inlineResponse2003.listenPort == null : this.listenPort.equals(inlineResponse2003.listenPort)) &&
        (this.isTrustedPeer == null ? inlineResponse2003.isTrustedPeer == null : this.isTrustedPeer.equals(inlineResponse2003.isTrustedPeer)) &&
        (this.connectedAt == null ? inlineResponse2003.connectedAt == null : this.connectedAt.equals(inlineResponse2003.connectedAt)) &&
        (this.unconfirmedVerifyTransaction == null ? inlineResponse2003.unconfirmedVerifyTransaction == null : this.unconfirmedVerifyTransaction.equals(inlineResponse2003.unconfirmedVerifyTransaction)) &&
        (this.id == null ? inlineResponse2003.id == null : this.id.equals(inlineResponse2003.id)) &&
        (this.state == null ? inlineResponse2003.state == null : this.state.equals(inlineResponse2003.state)) &&
        (this.userAgent == null ? inlineResponse2003.userAgent == null : this.userAgent.equals(inlineResponse2003.userAgent)) &&
        (this.height == null ? inlineResponse2003.height == null : this.height.equals(inlineResponse2003.height));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.lastReceived == null ? 0: this.lastReceived.hashCode());
    result = 31 * result + (this.lastSent == null ? 0: this.lastSent.hashCode());
    result = 31 * result + (this.outgoing == null ? 0: this.outgoing.hashCode());
    result = 31 * result + (this.mirror == null ? 0: this.mirror.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.listenPort == null ? 0: this.listenPort.hashCode());
    result = 31 * result + (this.isTrustedPeer == null ? 0: this.isTrustedPeer.hashCode());
    result = 31 * result + (this.connectedAt == null ? 0: this.connectedAt.hashCode());
    result = 31 * result + (this.unconfirmedVerifyTransaction == null ? 0: this.unconfirmedVerifyTransaction.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.userAgent == null ? 0: this.userAgent.hashCode());
    result = 31 * result + (this.height == null ? 0: this.height.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("  lastReceived: ").append(lastReceived).append("\n");
    sb.append("  lastSent: ").append(lastSent).append("\n");
    sb.append("  outgoing: ").append(outgoing).append("\n");
    sb.append("  mirror: ").append(mirror).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  listenPort: ").append(listenPort).append("\n");
    sb.append("  isTrustedPeer: ").append(isTrustedPeer).append("\n");
    sb.append("  connectedAt: ").append(connectedAt).append("\n");
    sb.append("  unconfirmedVerifyTransaction: ").append(unconfirmedVerifyTransaction).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  userAgent: ").append(userAgent).append("\n");
    sb.append("  height: ").append(height).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
