/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2001 {
  
  @SerializedName("csrf_token")
  private String csrfToken = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCsrfToken() {
    return csrfToken;
  }
  public void setCsrfToken(String csrfToken) {
    this.csrfToken = csrfToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return (this.csrfToken == null ? inlineResponse2001.csrfToken == null : this.csrfToken.equals(inlineResponse2001.csrfToken));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.csrfToken == null ? 0: this.csrfToken.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("  csrfToken: ").append(csrfToken).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
