/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse200 {
  
  @SerializedName("hours")
  private Long hours = null;
  @SerializedName("coins")
  private Integer coins = null;
  @SerializedName("uxid")
  private String uxid = null;
  @SerializedName("owner_address")
  private String ownerAddress = null;
  @SerializedName("spent_block_seq")
  private Integer spentBlockSeq = null;
  @SerializedName("spent_tx")
  private String spentTx = null;
  @SerializedName("time")
  private Long time = null;
  @SerializedName("src_block_seq")
  private Long srcBlockSeq = null;
  @SerializedName("src_tx")
  private String srcTx = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getHours() {
    return hours;
  }
  public void setHours(Long hours) {
    this.hours = hours;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCoins() {
    return coins;
  }
  public void setCoins(Integer coins) {
    this.coins = coins;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUxid() {
    return uxid;
  }
  public void setUxid(String uxid) {
    this.uxid = uxid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOwnerAddress() {
    return ownerAddress;
  }
  public void setOwnerAddress(String ownerAddress) {
    this.ownerAddress = ownerAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSpentBlockSeq() {
    return spentBlockSeq;
  }
  public void setSpentBlockSeq(Integer spentBlockSeq) {
    this.spentBlockSeq = spentBlockSeq;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSpentTx() {
    return spentTx;
  }
  public void setSpentTx(String spentTx) {
    this.spentTx = spentTx;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getTime() {
    return time;
  }
  public void setTime(Long time) {
    this.time = time;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getSrcBlockSeq() {
    return srcBlockSeq;
  }
  public void setSrcBlockSeq(Long srcBlockSeq) {
    this.srcBlockSeq = srcBlockSeq;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSrcTx() {
    return srcTx;
  }
  public void setSrcTx(String srcTx) {
    this.srcTx = srcTx;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return (this.hours == null ? inlineResponse200.hours == null : this.hours.equals(inlineResponse200.hours)) &&
        (this.coins == null ? inlineResponse200.coins == null : this.coins.equals(inlineResponse200.coins)) &&
        (this.uxid == null ? inlineResponse200.uxid == null : this.uxid.equals(inlineResponse200.uxid)) &&
        (this.ownerAddress == null ? inlineResponse200.ownerAddress == null : this.ownerAddress.equals(inlineResponse200.ownerAddress)) &&
        (this.spentBlockSeq == null ? inlineResponse200.spentBlockSeq == null : this.spentBlockSeq.equals(inlineResponse200.spentBlockSeq)) &&
        (this.spentTx == null ? inlineResponse200.spentTx == null : this.spentTx.equals(inlineResponse200.spentTx)) &&
        (this.time == null ? inlineResponse200.time == null : this.time.equals(inlineResponse200.time)) &&
        (this.srcBlockSeq == null ? inlineResponse200.srcBlockSeq == null : this.srcBlockSeq.equals(inlineResponse200.srcBlockSeq)) &&
        (this.srcTx == null ? inlineResponse200.srcTx == null : this.srcTx.equals(inlineResponse200.srcTx));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.hours == null ? 0: this.hours.hashCode());
    result = 31 * result + (this.coins == null ? 0: this.coins.hashCode());
    result = 31 * result + (this.uxid == null ? 0: this.uxid.hashCode());
    result = 31 * result + (this.ownerAddress == null ? 0: this.ownerAddress.hashCode());
    result = 31 * result + (this.spentBlockSeq == null ? 0: this.spentBlockSeq.hashCode());
    result = 31 * result + (this.spentTx == null ? 0: this.spentTx.hashCode());
    result = 31 * result + (this.time == null ? 0: this.time.hashCode());
    result = 31 * result + (this.srcBlockSeq == null ? 0: this.srcBlockSeq.hashCode());
    result = 31 * result + (this.srcTx == null ? 0: this.srcTx.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("  hours: ").append(hours).append("\n");
    sb.append("  coins: ").append(coins).append("\n");
    sb.append("  uxid: ").append(uxid).append("\n");
    sb.append("  ownerAddress: ").append(ownerAddress).append("\n");
    sb.append("  spentBlockSeq: ").append(spentBlockSeq).append("\n");
    sb.append("  spentTx: ").append(spentTx).append("\n");
    sb.append("  time: ").append(time).append("\n");
    sb.append("  srcBlockSeq: ").append(srcBlockSeq).append("\n");
    sb.append("  srcTx: ").append(srcTx).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
