/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Apiv1wallettransactionHoursSelection;
import org.openapitools.client.model.Apiv1wallettransactionTo;
import org.openapitools.client.model.Apiv1wallettransactionWallet;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineObject {
  
  @SerializedName("change_address")
  private String changeAddress = null;
  @SerializedName("hours_selection")
  private Apiv1wallettransactionHoursSelection hoursSelection = null;
  @SerializedName("ignore_unconfirmed")
  private Boolean ignoreUnconfirmed = null;
  @SerializedName("to")
  private List<Apiv1wallettransactionTo> to = null;
  @SerializedName("wallet")
  private Apiv1wallettransactionWallet wallet = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getChangeAddress() {
    return changeAddress;
  }
  public void setChangeAddress(String changeAddress) {
    this.changeAddress = changeAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Apiv1wallettransactionHoursSelection getHoursSelection() {
    return hoursSelection;
  }
  public void setHoursSelection(Apiv1wallettransactionHoursSelection hoursSelection) {
    this.hoursSelection = hoursSelection;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIgnoreUnconfirmed() {
    return ignoreUnconfirmed;
  }
  public void setIgnoreUnconfirmed(Boolean ignoreUnconfirmed) {
    this.ignoreUnconfirmed = ignoreUnconfirmed;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Apiv1wallettransactionTo> getTo() {
    return to;
  }
  public void setTo(List<Apiv1wallettransactionTo> to) {
    this.to = to;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Apiv1wallettransactionWallet getWallet() {
    return wallet;
  }
  public void setWallet(Apiv1wallettransactionWallet wallet) {
    this.wallet = wallet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject inlineObject = (InlineObject) o;
    return (this.changeAddress == null ? inlineObject.changeAddress == null : this.changeAddress.equals(inlineObject.changeAddress)) &&
        (this.hoursSelection == null ? inlineObject.hoursSelection == null : this.hoursSelection.equals(inlineObject.hoursSelection)) &&
        (this.ignoreUnconfirmed == null ? inlineObject.ignoreUnconfirmed == null : this.ignoreUnconfirmed.equals(inlineObject.ignoreUnconfirmed)) &&
        (this.to == null ? inlineObject.to == null : this.to.equals(inlineObject.to)) &&
        (this.wallet == null ? inlineObject.wallet == null : this.wallet.equals(inlineObject.wallet));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.changeAddress == null ? 0: this.changeAddress.hashCode());
    result = 31 * result + (this.hoursSelection == null ? 0: this.hoursSelection.hashCode());
    result = 31 * result + (this.ignoreUnconfirmed == null ? 0: this.ignoreUnconfirmed.hashCode());
    result = 31 * result + (this.to == null ? 0: this.to.hashCode());
    result = 31 * result + (this.wallet == null ? 0: this.wallet.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject {\n");
    
    sb.append("  changeAddress: ").append(changeAddress).append("\n");
    sb.append("  hoursSelection: ").append(hoursSelection).append("\n");
    sb.append("  ignoreUnconfirmed: ").append(ignoreUnconfirmed).append("\n");
    sb.append("  to: ").append(to).append("\n");
    sb.append("  wallet: ").append(wallet).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
