/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Apiv1exploreraddressInputs;
import org.openapitools.client.model.Apiv1exploreraddressOutputs;
import org.openapitools.client.model.Apiv1exploreraddressStatus;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2002 {
  
  @SerializedName("outputs")
  private List<Apiv1exploreraddressOutputs> outputs = null;
  @SerializedName("inner_hash")
  private String innerHash = null;
  @SerializedName("inputs")
  private List<Apiv1exploreraddressInputs> inputs = null;
  @SerializedName("fee")
  private Integer fee = null;
  @SerializedName("sigs")
  private List<String> sigs = null;
  @SerializedName("length")
  private Long length = null;
  @SerializedName("txid")
  private String txid = null;
  @SerializedName("type")
  private Integer type = null;
  @SerializedName("status")
  private Apiv1exploreraddressStatus status = null;
  @SerializedName("timestamp")
  private Integer timestamp = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Apiv1exploreraddressOutputs> getOutputs() {
    return outputs;
  }
  public void setOutputs(List<Apiv1exploreraddressOutputs> outputs) {
    this.outputs = outputs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInnerHash() {
    return innerHash;
  }
  public void setInnerHash(String innerHash) {
    this.innerHash = innerHash;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Apiv1exploreraddressInputs> getInputs() {
    return inputs;
  }
  public void setInputs(List<Apiv1exploreraddressInputs> inputs) {
    this.inputs = inputs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getFee() {
    return fee;
  }
  public void setFee(Integer fee) {
    this.fee = fee;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getSigs() {
    return sigs;
  }
  public void setSigs(List<String> sigs) {
    this.sigs = sigs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getLength() {
    return length;
  }
  public void setLength(Long length) {
    this.length = length;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTxid() {
    return txid;
  }
  public void setTxid(String txid) {
    this.txid = txid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getType() {
    return type;
  }
  public void setType(Integer type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Apiv1exploreraddressStatus getStatus() {
    return status;
  }
  public void setStatus(Apiv1exploreraddressStatus status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return (this.outputs == null ? inlineResponse2002.outputs == null : this.outputs.equals(inlineResponse2002.outputs)) &&
        (this.innerHash == null ? inlineResponse2002.innerHash == null : this.innerHash.equals(inlineResponse2002.innerHash)) &&
        (this.inputs == null ? inlineResponse2002.inputs == null : this.inputs.equals(inlineResponse2002.inputs)) &&
        (this.fee == null ? inlineResponse2002.fee == null : this.fee.equals(inlineResponse2002.fee)) &&
        (this.sigs == null ? inlineResponse2002.sigs == null : this.sigs.equals(inlineResponse2002.sigs)) &&
        (this.length == null ? inlineResponse2002.length == null : this.length.equals(inlineResponse2002.length)) &&
        (this.txid == null ? inlineResponse2002.txid == null : this.txid.equals(inlineResponse2002.txid)) &&
        (this.type == null ? inlineResponse2002.type == null : this.type.equals(inlineResponse2002.type)) &&
        (this.status == null ? inlineResponse2002.status == null : this.status.equals(inlineResponse2002.status)) &&
        (this.timestamp == null ? inlineResponse2002.timestamp == null : this.timestamp.equals(inlineResponse2002.timestamp));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.outputs == null ? 0: this.outputs.hashCode());
    result = 31 * result + (this.innerHash == null ? 0: this.innerHash.hashCode());
    result = 31 * result + (this.inputs == null ? 0: this.inputs.hashCode());
    result = 31 * result + (this.fee == null ? 0: this.fee.hashCode());
    result = 31 * result + (this.sigs == null ? 0: this.sigs.hashCode());
    result = 31 * result + (this.length == null ? 0: this.length.hashCode());
    result = 31 * result + (this.txid == null ? 0: this.txid.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("  outputs: ").append(outputs).append("\n");
    sb.append("  innerHash: ").append(innerHash).append("\n");
    sb.append("  inputs: ").append(inputs).append("\n");
    sb.append("  fee: ").append(fee).append("\n");
    sb.append("  sigs: ").append(sigs).append("\n");
    sb.append("  length: ").append(length).append("\n");
    sb.append("  txid: ").append(txid).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
